# Site settings
title: Kyla Gold - Gay Wedding Planning & Design
email: KYLA@KYLAGOLD.COM
url: https://www.kylagold.com
description: "Kyla Gold - Gay Wedding Planning & Design"
phone: "(415) 646-6123"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#c1ad73' #D4AF37
  brand-heading: '#c1ad73'

font:
  brand-heading: "Rambla, sans-serif"
  #contact: "alice, serif"
  contact: "Rambla, sans-serif"
  #intro-text: "meddon, cursive"
  intro-text: "Rambla, sans-serif"

# Footer settings
footer: "Kyla Childress"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  title: "pinterest"
  url: "http://www.pinterest.com/kylagold"

# Build settings
markdown: kramdown
permalink: pretty
